# Generated by Django 4.0.6 on 2022-07-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='arrival_plan',
        ),
    ]
