# Generated by Django 4.0.6 on 2022-07-08 02:51

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
    ]
