# Generated by Django 4.0.6 on 2022-07-16 13:18

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
    ]
