# Generated by Django 4.0.6 on 2022-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_city_remove_event_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/images/default-event-2-min.jpg', upload_to='events/images'),
        ),
    ]
