# Generated by Django 4.0.6 on 2022-07-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/defaults/default-user.jpeg', upload_to='accounts/images/'),
        ),
    ]
