# Generated by Django 4.0.6 on 2022-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
